name: Playwright Tests
on:
  push:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: always() # Esto es CLAVE: asegura que el reporte se suba aunque fallen los tests
      with:
        name: mi-reporte-html
        path: playwright-report/index.html # Cambia esto por la ruta y nombre de tu archivo HTML
        retention-days: 7
